### ISSUE TITLE
Response from CRAN

### ISSUE THREAD

**Issue by TengMCing** [TengMCing/spotoroo#14]
<details>

<summary> EMAIL </summary>

Thanks,

Please add a few more details about the package functionality and
implemented methods in your Description text.

If there are references describing the methods in your package, please
add these in the description field of your DESCRIPTION file in the form
authors (year) <doi:...>
authors (year) <arXiv:...>
authors (year, ISBN:...)
or if those are not available: <https:...>
with no space after 'doi:', 'arXiv:', 'https:' and angle brackets for
auto-linking.
(If you want to add a title as well please put it in quotes: "Title")

Please add \value to .Rd files regarding exported methods and explain
the functions results in the documentation. Please write about the
structure of the output (class) and also what the output means. (If a
function does not return a value, please document that too, e.g.
\value{No return value, called for side effects} or similar)
Missing Rd-tags:
      plot_vic_map.Rd: \arguments
      plot.spotoroo.Rd: \value
      print.spotoroo.Rd: \value
      summary_spotoroo.Rd: \value
      summary.spotoroo.Rd: \value

Please fix and resubmit.

Best,
Gregor Seyer

Am 19.02.21 um 06:52 schrieb CRAN submission:

</details>

---

## TODO

**REVISE:**

- [x] modify DESCRIPTION (add reference? unclear what I should do.)
- [x] plot_vic_map.Rd: \arguments
- [x] plot.spotoroo.Rd: \value
- [x] print.spotoroo.Rd: \value
- [x] summary_spotoroo.Rd: \value
- [x] summary.spotoroo.Rd: \value
- [x] check all other Rd files

**TEST:**

- [x] Win-builder
    - [x] devel
    - [x] oldrel
    - [x] release
- [x] R-hub
    - [x] Ubuntu Linux
        - [x] devel
        - [x] release
    - [x] Debian Linux
        - [x] devel
        - [x] release
    - [x] Fedora Linux
        - [x] devel
    - [x] MAC
        - [x] release
    - [x] Windows 
        - [x] oldrel
        - [x] devel
        - [x] release

**Comment by TengMCing** [comment]
done
